# Deve ser único no servidor SonarQube
sonar.projectKey=meu-projeto
sonar.projectName="Meu Projeto"
sonar.projectVersion=1.0

# Caminho do código fonte (relativo ao arquivo)
sonar.sources=.frontend,projeto_backend
# Caminho dos testes (relativo ao arquivo)
sonar.tests=backend/tests

# Codificação dos arquivos fonte
sonar.sourceEncoding=UTF-8

# Excluir diretórios
sonar.exclusions=**/node_modules/**,**/*.min.js,**/vendor/**,**/tests/**

# Linguagem principal (opcional)
sonar.language=py,js  # Para Python, por exemplo