# Generated by Django 5.2.1 on 2025-06-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='condicao',
            field=models.CharField(blank=True, help_text='Descrição da condição do produto (ex: novo, usado, etc.)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do produto em R$', max_digits=10),
        ),
    ]
