# Generated by Django 5.2.1 on 2025-06-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_condicao_produto_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade_atual',
        ),
        migrations.AddField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
