# Generated by Django 5.2 on 2025-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuário Comum')], default='usuario', max_length=20)),
            ],
        ),
    ]
